---
title: "📑 Publications"
format: html
---

- You can also explore my work on [Google Scholar](https://scholar.google.com/citations?user=TgdOb8MAAAAJ).
- Some of the work may be available on [ResearchGate](https://www.researchgate.net/profile/Gihun-Im) in its accepted version.
- \[KCI\] denotes the [Korean Citation Index](https://www.kci.go.kr/kciportal/main.kci?locale=en), indicating that the article is in Korean.

\

## 2026

**Im, G.** (2026). Ethical risk prevention in client generative AI use: Applying the primary risk-management model. *American Psychologist*. Advance online publication. <https://doi.org/10.1037/amp0001731> 

**Im, G.** (under review). Outing-related threat and depression among sexual minority adults during the COVID-
19 pandemic: Internalized homophobia and the dual role of community connectedness.

Kim, I., **Im, G.**, Min, Y., & Ding, R. (under review). Ambivalent engagement with generative AI: Greater mental
health use and concern among college students with anxiety-depression.

Kim, J., Kang, S., **Im, G.**, & Kim, M. (under review). A systematic review and meta-synthesis on LGBTQ+ partner bereavement: Grief trajectories toward an ecological framework.

**Im, G.**, Case, A. S., Bae, I., Ji, S., Tang, Y., & Zhang, Y. (under review). User engagement with ChatGPT for
mental health support: A mixed-method meta-analysis.

**Im, G.**, & Kim, D. (under review). Korean school counselors' counseling competencies and advocacy activities for LGBTQ+ youth: A latent profile analysis.

## 2025

Kim, D., **Im, G.**, Chung, G., & Park, J. (2025). Impact of discussion activity in international youth exchange programs on global citizenship: Mediating role of multicultural competence. *Journal of Education & Culture*, *31*(1), 597–613. [\[KCI\]](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART003179605)

Kim, D., Park, J., & **Im, G.** (2025). Research on developing a social enrichment program for young adults with borderline intellectual functioning. *Disability & Employment*, *35*(1), 163–186. [\[KCI\]](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART003177743)

## 2023

Kim, D., Park, J., Lee, J., Park, I., & **Im, G.** (2023). Exploring subjects of standardized curriculum for youth counselors in South Korea by Delphi method. *Studies on Korean Youth*, *34*(4), 143–164. <https://doi.org/10.14816/sky.2023.34.4.143> \[KCI\]
