---
title: "Impact of discussion activity in international youth exchange programs on global citizenship: Mediating role of multicultural competence"
author: "Kim, D., Park, J., Im, G., & Chung, G."
author-title: author(s)
year: "2025"
publication: "Journal of Education & Culture"
doi: "https://doi.org/10.24159/joec.2025.31.1.597"
pdf: 
toc: false
categories:
  - Article
  - KCI
---

::: {.callout-note appearance = "simple"}

## Citation (APA 7th)

Kim, D., Im, G., & Chung, G., Park, J. (2025). Impact of discussion activity in international youth exchange programs on global citizenship: Mediating role of multicultural competence. *Journal of Education & Culture*, *31*(1), 597-613.

:::

#### Abstract

This study explored the impact of participation in discussion activities within international youth exchange programs on global citizenship, focusing on the mediating role of multicultural competence. We collected and analyzed data using responses from 75 participants across 41 countries who completed pre- and post-program surveys. Correlation analysis was followed by mediation analysis. Sensitivity analysis was performed to assess the robustness of the mediation effect. The key findings are as follows. First, multicultural competence partially mediated the relationship between discussion activity and global citizenship. Second, sensitivity analysis showed that the direct effect was robust, while the indirect effect was sensitive to omitted confounders. These findings provide insights into the role of discussion activities in fostering global citizenship. Finally, we discussed the implications, limitations, and directions for future research.