---
title: "Research on developing a social enrichment program for young adults with borderline intellectual functioning"
author: "Kim, D., Park, J., & Im, G."
author-title: author(s)
year: "2025"
publication: "Disability & Employment"
doi: "https://doi.org/10.15707/disem.2025.35.1.07"
pdf: assets/pdf/dkim2025_2.pdf
toc: false
categories:
  - Article
  - KCI
---

::: {.callout-note appearance = "simple"}

## Citation (APA 7th)

Kim, D., Park, J., & Im, G. (2025). Research on developing a social enrichment program for young adults with borderline intellectual functioning. *Disability & Employment*, *35*(1), 163-186.

:::

#### Abstract

- **Objectives**: People with borderline intellectual functioning (BIF) have difficulty forming and maintaining relationships with others. These traits make it difficult for young adults with BIF to transition into adulthood, including academic careers and employment. However, there is still a lack of programs promoting social competence for them. Therefore, this study aims to develop a program to support the social development of young adults with BIF. 
- **Method**: To this end, this study first conducted a literature review to identify the components of social enrichment programs. Then, we implemented a needs assessment among the subjects. Based on the results of the literature review and needs analysis, we developed a social enrichment program based on social emotional learning (SEL), cognitive behavioral therapy (CBT), and dialectical behavior therapy (DBT) for a total of 12 sessions. To pilot the program, we asked for cooperation from two organizations that support people with borderline intellectual functioning and recruited three instructors and 11 participants for the pilot. After piloting the program, we identified changes in participants' social factors and conducted interviews to explore their experiences with the program. Based on the results of the pilot, we refined the program and developed the final program. 
- **Results**: Participants' social awareness post-test scores increased significantly after participating in the program. Observer responses showed significant gains in all factors of the social competence scale. Analysis of participant interviews revealed that participants learned how to communicate and get along with people after participating in the program. 
- **Implications**: This study is noteworthy because it developed a program to strengthen the social skills of young adults with BIF and validated the program's applicability in the field through a pilot study.