---
title: "Korean school counselors' counseling competencies and advocacy activities for LGBTQ+ youth: Latent Profile Analysis"
author: "Im, G., & Kim, D."
author-title: author(s)
year: "under review"
publication: "Current Psychology"
doi: ""
pdf: 
toc: false
categories:
  - Article
  - Under Review
---

::: {.callout-note appearance = "simple"}

## Citation (APA 7th)

Im, G., & Kim, D. (under review). Korean school counselors' counseling competencies and advocacy activities for LGBTQ+ youth: Latent Profile Analysis.

:::

#### Abstract

The purpose of this study was to classify school counselors into latent groups based on their counseling competencies and advocacy activities for LGBTQ+ youth, and to explore the effects of certain characteristics on the classifications. A comprehensive survey was given to 259 school counselors. Using Latent Profile Analysis (LPA), the data was classified into potential groups, and subsequent analysis with the R3STEP method identified factors that significantly influenced group classification. Data analysis via LPA revealed five latent groups among school counselors, labeled as "Distant," "Passive," "Average," "Active," and "Advocacy-oriented." Factors that influenced the classification of the groups included sexual orientation and gender identity, the logarithmic value of counseling experiences with LGBTQ+ clients, and school level advocacy. The findings led to discussions on educational and training approaches to enhance school counselors’ counseling competencies and advocacy activities for LGBTQ+ youth.
