---
title: Cross-Cultural Application of PWT to Korean LGB People
date: "2022-09"
author: "Finished"
date-format: "MMM YYYY"
published-title: "started"
author-title: "state"
description: In collaboration with Equity in Counseling Research (ECR) team
categories: 
  - Career
  - LGBTQ+
  - PWT
format: html
editor: visual
filters:
  - highlight-text
---

The Psychology of Working Theory (PWT; [Duffy et al., 2016](https://www.drryanduffy.com/uploads/3/1/7/2/31724447/duffy_et_al.__2016__pwt.pdf))[^1] helps us understand how social and economic factors affect people's career decisions and job outcomes. It highlights the challenges posed by social marginalization and economic constraints in achieving **decent work**---a type of work that contributes to well-being and access to opportunities.

[^1]: Duffy, R. D., Blustein, D. L., Diemer, M. A., & Autin, K. L. (2016). The Psychology of Working Theory. *Journal of Counseling Psychology*, *63*(2), 127-148.

In South Korea, LGB people face significant discrimination and marginalization, especially in the workplace. Many experience mistreatment like bullying, intimidation, or even job loss due to their sexual orientation. This discrimination creates additional stress, known as **minority stress**, which can negatively affect both mental health and career outcomes. Despite this, there is limited research on how these experiences impact the work volition of LGB people in South Korea.

Based on the PWT, we examined how social class and and marginalization influence work volition among LGB people in South Korea. We also explored how factors like social support and positive LGB identity can reduce the negative impact of these challenges.

[Our paper is under review.]{color="#FFD479"}

::: {.callout-note appearance = "simple"}

## Related Works

-   Ko, J., Park, J., & **Im, G.**, Cheung, S., & Reid-Marks, L. (2024, August 8-10). *Social stigma, social status, work volition, social support, and positive identity in LGB college students in Korea*. Poster presented at the APA 2024 Convention, Seattle, WA, United States.

:::
